# This file was generated by GoReleaser. DO NOT EDIT.
cask "fairway" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "07a663b4117ff67078cdaeb448c4c1da6fc01844693e082e56e56c18df0e06ac"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "deed977a9f53de76dca19360ffff0ea52bef08ab0bdd52aa9be0fb47e03f687c"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc20e0a553884786361bb031a90d9bd187c0fdfd24c45e07d70a111c77ef655e"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "853d21c4a306c8e1a052252860089021fb7e00130a41cd86b1ad2d1bded1be21"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fairway"
  desc "Coordination control plane for governed agentic engineering"
  homepage "https://fairway.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fairway"

  # No zap stanza required

end
