# This file was generated by GoReleaser. DO NOT EDIT.
cask "fairway" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6010c01d6c230d03b3590a1a3cc2abd4f5324746a50a3c9f23fe59daae7e432b"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1112ffccd5ac858388de4402f86e9bf991cc9dc2a166eee4d9af94f0726a2c5f"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "203a8aa98eccb4fdbe33199dc27ffc4c67e7018700e09f17b353dfd5cb74c3e1"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "993a30f2389f495d0302e83a077c498b4f295572343074877a69ed2bcde522be"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fairway"
  desc "Traffic control for coding agents"
  homepage "https://fairway.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fairway"

  # No zap stanza required

end
