# This file was generated by GoReleaser. DO NOT EDIT.
cask "fairway" do
  version "0.1.13"

  on_macos do
    on_intel do
      sha256 "e00721a86c99a4e065df744b1546585b0679f8fe7b77d1e7d8ebf49779ebd101"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "af531c1da2dae04074a6785a2dcea3fa28d4aca4f55485a63c9f406d54f37c64"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "202a74718319deeec7a48151550f2cb9b5c475fa8488aba16afe11f7d261eb3d"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f2b32b3b5b9bcb6f35dec4bcd34de3da93f6763864e65ece894779f3e6ded8f"
      url "https://github.com/fairway-run/fairway/releases/download/v#{version}/fairway_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fairway"
  desc "Engineering control and accountability for agent-driven delivery"
  homepage "https://fairway.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fairway"

  # No zap stanza required

end
